### ISSUE TITLE
Tool being labelled a "cheat" by Eternal Twitch Community

### ISSUE THREAD

**Issue by Chesspieceface** [extesy/DeckTracker#170]
I have used your tool on stream since release, and now again that it is fixed for Eternal.  SDSakuragi came in today to tell me that because it reveals a few instances of information that should not be known to the player (in two rare cases) it is being treated as a cheat and people have attempted to cause twitch bans for this.  Either DWD needs to hide this data from you or you need to release a "safe version" that is for streamers and shows only static deck lists without subtractions or additions or this tool is basically going to be abandoned by force.  I would love to see you fix this as I really like it for my stream.

**Comment by extesy** [comment]
@Chesspieceface This is essentially the same issue as #152. I've reported the bug to Scarlatch (CEO of DWD) several weeks ago and he's been ignoring me ever since.

Be aware that similar issue exists for TESL game and I have thousands of active players and tons of twitch streamers using it and nobody had reported any problems in the past year.
