### ISSUE TITLE
Can't connect to ESL/No overlay

### ISSUE THREAD

**Issue by JStoneWrites** [extesy/DeckTracker#171]
I know there's an existing issue (5 I believe?) related to things not working. However, I seem to be getting a different error in my logs than what I saw listed there, so thought I'd make an issue to see if there's something I've overlooked...

exception in firewall
tried both bethesda launcher and steam
disabled AV

Not sure what I might be missing or if it's just a part of the existing issue.

[events.log](https://github.com/extesy/DeckTracker/files/1626455/events.log)

**Comment by JStoneWrites** [comment]
@extesy something in 1.0.76 or 1.0.77 seems to have fixed this. 

Green text, overlay on, looking good!

**Comment by extesy** [comment]
Sounds good! Closing the ticket :)

**Comment by JStoneWrites** [comment]
@extesy sorry to tag you in again, but wasn't sure if you'd see otherwise...

I reset the computer the other day and tracker stopped working. Got curious and started poking at apps that might have not been running the first time...

I found the problem... SkyFonts...

For some reason, when SkyFonts is running, Universal Deck Tracker cannot connect to either the Steam or Bethesda Launcher versions of TESL on Windows 10 Home x64.

Close it, and restart the tracker/game and it connects instantly...

Is there any logs I can send you or the like to test on your end and see if this is an isolated issue with something on my end or something that other's might be experiencing? I don't mind closing SkyFonts, so it's still resolved IMO, but if it's a bug somewhere or an incompatibility, happy to help give you information to squash it.

**Comment by extesy** [comment]
Windows is a very complicated platform and the number of possible software combinations is infinite. It's impossible to predict if some software might introduce a weird conflict because of the way it injects itself into Windows.

It's great that you found it on your machine, but unfortunately there's no way to solve this problem for everybody at once. The logs from deck tracker won't help either because when something goes wrong there's no way to know what exactly caused the conflict.

Anyways, thanks for the follow up! I'm glad it works for you now.
