### ISSUE TITLE
Crashes TES: Legends after Morrowind update

### ISSUE THREAD

**Issue by DeathofSouls** [extesy/DeckTracker#194]
After the TES: Legends update for Morrowind, Deck Tracker crashes the game.

**Comment by neuroaktivo** [comment]
+1 plzzz update deck tracker for morrowind plzz.

**Comment by lljbash** [comment]
+1 thx

**Comment by steelguardian53** [comment]
+1

**Comment by Krapulax80** [comment]
+1

**Comment by Middlemist** [comment]
same problem

**Comment by mortulon** [comment]
First thing to say: I thank you guys for the good work. I really like your tool. Well done!

Second thing to say: +1 :)

**Comment by DanoLefourbe** [comment]
Same thing here. And thanks for your work :)

**Comment by mortulon** [comment]
Thank you for that information MajorButtScratch. An update of "Universal Deck Tracker" from version 1.0.74 to 1.0.75 has solved the problem for me. (I have to start "Universal Deck Tracker" before launching "TES: Legends", otherwise I get the error message "Installation has failed".)

**Attention:** Some people encounter problems when using the import and export functionality of "Universal Deck Tracker" version 1.0.75. It seems that these problems are associated with the new "Houses of Morrowind" cards somehow. For further information see issue [https://github.com/extesy/DeckTracker/issues/195](https://github.com/extesy/DeckTracker/issues/195). (I don't have "Houses of Morrowind" cards yet.)

**Comment by KopisGaming** [comment]
+1

**Comment by Kabada1** [comment]
1.0.75 doesn't crash the game anymore, sure, but Iit also can't handle the new 3-color decks. Will there be an update?

**Comment by KopisGaming** [comment]
@Kabada1 I dont know, but I hope so. I need the tracker BADLY for a variety of reasons.

**Comment by MajorButtScratch** [comment]
It doesn't work as well as it used to, I'm now seeing it fail regularly to populate my deck properly during a game (only shows the cards I draw), BUT, it did seem to work briefly, even with 3-colour decks when I played in Solo Arena with it. Haven't pinned down what the sequence is to make it work or not.

**Comment by extesy** [comment]
Fixed in `1.0.76`.

**Comment by KopisGaming** [comment]
Much appreciated, extesy. :)
