### ISSUE TITLE
buttons greyed out, detects game is in red.

### ISSUE THREAD

**Issue by midstorm** [extesy/DeckTracker#226]
1) was working fine the day before yesterday
2) yesterday started up, goes blue, flashes red a couple times, the goes red when I start a game.
3)added exceptions to SEP antivirus, etc..
4) uninstalled and reinstalled
5)still doing it
6)made a new ticket yesterday, no word from developer, just deleted my ticket.
7) I have the fix mentioned in the other post, that is why it was working before.

**Comment by extesy** [comment]
@midstorm What game are you starting?

**Comment by midstorm** [comment]
I am trying to use UDT with Elder Scrolls Legends.
I am playing from within Steam.
This is on an HP laptop, Intel Core i5-4330M CPU with double 2.8 GHz 
let me know how to get any logs and I'll attach them.
Thanks

**Comment by extesy** [comment]
@midstorm Please see https://github.com/extesy/DeckTracker#reporting-problems section about how to provide logs.

**Comment by midstorm** [comment]
[error.log](https://github.com/extesy/DeckTracker/files/2092134/error.log)
[events.log](https://github.com/extesy/DeckTracker/files/2092137/events.log)
[games.log](https://github.com/extesy/DeckTracker/files/2092138/games.log)

Thanks Oleg, hopefully you can make sense of my problem, it came up yesterday no prob, down again today. If there's a conflicting program I can close it if I had some clue what it was...

**Comment by midstorm** [comment]
OK, thought I might come up with a fix myself, and Oleg I really appreciate your time I know this is freeware so its not always rewarding; Thank you.
The fix for my situation is to go to my download folder, re-install Microsoft access runtime, and in the options choose "repair" then reboot the computer.
This works well.
-Midstorm

**Comment by Danzyvor** [comment]
Hello, I am sorry for the stupid question, but can you explain again what you did to fix the problem? I am having the same problem, started yesterday. thank you.

**Comment by LordUber** [comment]
What game are you using it for? It's not working for Eternal at the moment and the author said he's not in any rush to update it.

**Comment by Danzyvor** [comment]
I`m playing Elder Scrolls Legends.

**Comment by extesy** [comment]
@Danzyvor Try reinstalling the package from the https://github.com/extesy/DeckTracker#known-issues first item.

**Comment by Danzyvor** [comment]
@extesy seems to have worked, thnak you.

**Comment by ksawerykarwacki** [comment]
@Danzyvor are you using access runtime x64 or x86? I have the same errors in events.txt but still cannot find way to get this working with legends.

**Comment by midstorm** [comment]
@ksawerykarwacki
Google "Microsoft Access runtime" it's free Microsoft software,  install it,  reboot your system,  start up tesl, then start up the deck tracker. 
If it doesn't work the first time,  open up your programs list,  select access runtime,  and repair it. 
Reboot,  try again,  tesl, then deck tracker.

**Comment by ksawerykarwacki** [comment]
@midstorm today morning finaly UDT injected correctly. I had some version of Access runtime 2016 (not sure if x86 or x64 i played with both yesterday for few hours)
But I had to uninstall it to reinstall Office 16 for some work (you cannot have both at the same time) i tried access runtime 2013 before unistalling office but it diddn't worked.

Then casually unistalled office and my nightmare begin:
- installed access runtime x64, reboot and try, couldn't inject UDT to Legends
- lunched repair, reboot, retry, couldn't inject UDT to Legends
- unistalled x64 and installed access runtime x86, reboot, retry, couldn't inject UDT to Legends
- unistalled x86 and reinstalled x64, reboot, retry, couldn't inject UDT to Legends

Doesn't matter if focus is on UDT or Legends windows, doesn't mater if I run regular UDT or elevated as admin.

If we cannot find real solution to this issue my best bet is to run factory reset of my system which sounds like overkill. 

I would say that this issue is far from being closed.
